There is the Tower of Pain, "Bellatra" in the desert of Navisko.
In Bellatra, users will pay for entrance depending on their level.
Users can get money back by hunting monsters. This is a survival
game which users can recieve their share of Bellatra's income while
also getting a management rights if users get a high score with 
more than 3 clan members.
In addition, users will be able get the honor of listing their name or 
their clan's name on the Ranking chart on Pristontale's homepage. 


