In PristonTale, you can party with other players during
game playing. Party can be from 2 to 6 players. Party
members will equally share the money and EXP gained from
monsters. Your level must be within 10 levels from the 
average of the party members' level. To invite a player
to the party, simply click on that player and then send
an invitation message by clicking the invite button on
right hand top.



