Joining the clan (chief character)
   *When a clan chief clicks the
    character he wishes to recruit
    , an invitation button will   
    appear on the right hand top.
    If that person accepts the 
    invitation, he will become a
    clan membrer.


Clan mark and introduction phrase (chief character)
   *Clan mark or introduction 
    phrase can be registered by 
    clicking the clan button on 
    the left side of the game
    launcher or at PristonTale 
    website. It is limited to 80
    texts and can upload a 32x32
    bmp image. The clan mark can 
    be modified by the tool 
    provided at the clan page.

    
Disbandment of clan (chief character)
  *Disbandment of clan can only be
   done by clan chief. If the clan
   becomes less than 6 persons and
   lasts for 10 days, it will be
   disband automatically.


Banishment of clan (chief character)
  *Only clan chief can expel a clan
   member. 

Secession of clan
  *To leave the clan, you need to
   go through the clan master's 
   menu. Once you leave the clan,
   all features regarding clan will
   disappear. 


Clan Chat
  *Clan chat is a feature that will
   send messages to all clan 
   members. You can simply do it by
   pressing a clan chat button on
   the bottom of the clan list or  
   using the 'Tab' key.


Union Core
  *Union core is used to transfer 
   to places among clan members.
   You can save a clan member's 
   name on the core and when it's
   used, you will be transferred to
   the place that person is. 
   However, if that person is in
   restricted areas or SOD, the 
   core will not work. You must 
   have at least 6 members in clan
   to use this core. 
