Congratulations! your level is up! as you level up, you can
receive 5 points at character's stats. your character will be
grown up by being divided stats evenly among power, spirit,
talent, agility, and health. now click C. you can divide stats
in the window of character info.
power = ATK, STM, recovery of STM, HP, absorb,
            and weight incresed 
spirit = magic ATK, MP, and recovery of MP incresed
talent = ATK RTG, ATK power, defense, STM, speed,
           and absorb increased 
agility = damage of shooting weapon, ATK RTG,
           and defense increased 
health = HP, recovery of HP, STM, weight,
           and recovery of MP incresed




