Have you heard of specialized items?
A specialized item provides higher performance when used by
a character of a certain tribe. The required skill abilities
differ between specialized items and unspecialized items, and
each specialized item's performance also differs.
You can identify a specialized item by the notes specifying
specialized quality under the specifications of the item 
with added skill abilities. 



