Have you ever heard the Force Orb? it is the ATK reinforcement
system raised great power when in battle after refining sheltom
through Force Master.
however you may have to aware of Force Orb well-matched to
your level. it is the reason that sort, capacity, and time of
maintenance are adopted differently according to your
character's level.
Lucidy    500  Lucidy force    1-19    added ATK POW  +2 300sec
Sereno   1000  Sereno force    1-29    added ATK POW  +4 300sec
Fadeo    2000  Fadeo force     1-39    added ATK POW  +7 300sec
Sparky   4000  Sparky force    1-49    added ATK POW +10 300sec
Raident  7000  Raident force   over 50 added ATK POW +15 500sec
Transparo 10K  Transparo force over 50 added ATK POW +25 700sec
Murky     20K  Murky force     over 50 added ATK POW +40 1800sec





